[RUIN-312], [RUIN-307] Update JSON converter and HTML strings to use the human readable ids
santosfamilyfoundation/RuinaMain pull request #168
Opened 2022-02-09 16:42 UTC by 18chowdhary

# Description

Previously, the HTML strings used to generate HTML and PDF versions of the report were not using the new human-readable IDs but instead relying on the old randomly-generated 8-character IDs from the spreadsheet. Additionally, every component was submitting its data using other randomly-generated ids. For consistency purposes, every component has been updated to submit data using the question's human-readable id, and all of the JSON converters have been updated to reference these ids when looking for the corresponding answers to populate the export format. I manually updated all the HTML strings (the templates for the HTML and PDF exports) to use the human-readable IDs, but there are still some old ids because I cannot tell which questions these ids correspond to.

# Testing
1. Start a new report.
2. Add 2 vehicles and one non-motorist.
3. Populate each of the forms. Make sure to answer a number of questions. Try filling out one text field, one number button selector, one multi-button selector, one single select dropdown, and one multi-select dropdown in each of the forms.
4. Export the form to a desired format. (Try HTML or PDF).
5. Confirm that the export worked correctly.

2022-02-10 18:27 UTC, KristinAoki commented
Issues that i found while filling out form
- Time autofill no longer appears to be working
- county doesn't register when state has been selected

2022-02-10 20:38 UTC, 18chowdhary commented
> When filling out the different forms, none of the information was populated. Even the part where the photo used to appear does not show up. I did notice that there were a lot of accepting errors that occurred when I was filling out various parts of the forms but didn't break the app.

I addressed this issue, and the dependencies and auto-fills should be working now! (I can guarantee that the county drop-down and the time autofill are working, unsure about the rest).

2022-02-10 23:34 UTC, KristinAoki commented on src/reducers/RoadReducer.js
> +            // console.log('question answered for road:', question)
delete these

2022-02-10 23:36 UTC, KristinAoki requested changes
The form is filled out. But when I look at the PDF preview only the road sections are present and the headers at the top of the form are no longer present. 

Also please delete all log statements that are commented out

2022-02-13 19:34 UTC, KristinAoki approved these changes

2022-02-14 15:31 UTC, merged